# -*- coding: utf-8 -*-
"""TamilNadu Weather Monitor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkb2I2zI-vmngipHNte0Up8jrCE64C3w
"""

!pip install gradio requests pandas pytz

tn_taluks = {
    "Ariyalur": [
        "Ariyalur", "Sendurai", "Udayarpalayam"
    ],

    "Chengalpattu": [
        "Chengalpattu", "Cheyyur", "Madurantakam",
        "Tambaram", "Thirukalukundram", "Tiruporur", "Vandalur"
    ],

    "Chennai": [
        "Alandur", "Ambattur", "Ayanavaram", "Egmore",
        "Guindy", "Madhavaram", "Mylapore",
        "Perambur", "Purasawalkam", "Sholinganallur",
        "Thiruvottiyur", "Tondiarpet", "Velachery"
    ],

    "Coimbatore": [
        "Anaimalai", "Annur", "Coimbatore North",
        "Coimbatore South", "Kinathukadavu",
        "Madukkarai", "Mettupalayam",
        "Perur", "Pollachi", "Sulur", "Valparai"
    ],

    "Cuddalore": [
        "Bhuvanagiri", "Chidambaram", "Cuddalore",
        "Kattumannarkoil", "Kurinjipadi",
        "Panruti", "Srimushnam", "Titakudi", "Veppur"
    ],

    "Dharmapuri": [
        "Dharmapuri", "Harur", "Karimangalam",
        "Nallampalli", "Palacode", "Pennagaram"
    ],

    "Dindigul": [
        "Attur", "Dindigul East", "Dindigul West",
        "Guziliamparai", "Kodaikanal",
        "Natham", "Nilakottai",
        "Oddanchatram", "Palani", "Vedasandur"
    ],

    "Erode": [
        "Anthiyur", "Bhavani", "Erode",
        "Gobichettipalayam", "Kodumudi",
        "Modakurichi", "Nambiyur",
        "Perundurai", "Sathyamangalam", "Thalavadi"
    ],

    "Kallakurichi": [
        "Chinnasalem", "Kallakurichi",
        "Kalvarayan Hills", "Sankarapuram",
        "Tirukkoyilur", "Ulundurpet"
    ],

    "Kanchipuram": [
        "Kanchipuram", "Kundrathur",
        "Sriperumbudur", "Uthiramerur", "Walajabad"
    ],

    "Kanyakumari": [
        "Agastheeswaram", "Kalkulam",
        "Killiyur", "Thiruvattar", "Thovalai", "Vilavancode"
    ],

    "Karur": [
        "Aravakurichi", "Karur",
        "Kadavur", "Krishnarayapuram", "Kulithalai"
    ],

    "Krishnagiri": [
        "Anchetty", "Bargur", "Denkanikottai",
        "Hosur", "Krishnagiri", "Pochampalli", "Shoolagiri"
    ],

    "Madurai": [
        "Madurai East", "Madurai North",
        "Madurai South", "Madurai West",
        "Melur", "Peraiyur", "Thirumangalam",
        "Usilampatti", "Vadipatti"
    ],

    "Mayiladuthurai": [
        "Kuthalam", "Mayiladuthurai", "Sirkazhi", "Tharangambadi"
    ],

    "Nagapattinam": [
        "Kilvelur", "Nagapattinam",
        "Thirukkuvalai", "Vedaranyam"
    ],

    "Namakkal": [
        "Kolli Hills", "Kumarapalayam",
        "Mohanoor", "Namakkal",
        "Paramathi Velur", "Rasipuram", "Sendamangalam"
    ],

    "Nilgiris": [
        "Coonoor", "Gudalur", "Kotagiri", "Kundah", "Ooty"
    ],

    "Perambalur": [
        "Alathur", "Kunnam", "Perambalur", "Veppanthattai"
    ],

    "Pudukkottai": [
        "Alangudi", "Aranthangi", "Avudaiyarkoil",
        "Gandarvakottai", "Iluppur",
        "Karambakudi", "Kulathur",
        "Manamelkudi", "Ponnamaravathi",
        "Pudukkottai", "Thirumayam"
    ],

    "Ramanathapuram": [
        "Kadaladi", "Kamuthi", "Mudukulathur",
        "Paramakudi", "Ramanathapuram",
        "Rameswaram", "Tiruvadanai"
    ],

    "Ranipet": [
        "Arakkonam", "Arcot", "Ranipet",
        "Sholingur", "Walajah"
    ],

    "Salem": [
        "Attur", "Edappadi", "Gangavalli",
        "Kadayampatti", "Mettur",
        "Omalur", "Salem",
        "Sankari", "Vazhapadi", "Yercaud"
    ],

    "Sivaganga": [
        "Devakottai", "Ilayankudi", "Kalaiyarkoil",
        "Karaikudi", "Manamadurai",
        "Singampunari", "Sivaganga", "Thirupuvanam"
    ],

    "Tenkasi": [
        "Alangulam", "Kadayanallur",
        "Sankarankovil", "Shenkottai",
        "Sivagiri", "Tenkasi", "Veerakeralamputhur"
    ],

    "Thanjavur": [
        "Budalur", "Kumbakonam", "Orathanadu",
        "Papanasam", "Pattukkottai",
        "Peravurani", "Thanjavur", "Thiruvaiyaru", "Thiruvidaimarudur"
    ],

    "Theni": [
        "Andipatti", "Bodinayakanur",
        "Periyakulam", "Theni", "Uthamapalayam"
    ],

    "Thoothukudi": [
        "Eral", "Ettayapuram", "Kovilpatti",
        "Ottapidaram", "Sattankulam",
        "Srivaikuntam", "Thoothukudi", "Tiruchendur"
    ],

    "Tiruchirappalli": [
        "Lalgudi", "Manachanallur",
        "Manapparai", "Marungapuri",
        "Musiri", "Srirangam",
        "Thiruchirappalli", "Thuraiyur"
    ],

    "Tirunelveli": [
        "Ambasamudram", "Cheranmahadevi",
        "Manur", "Nanguneri",
        "Palayamkottai", "Radhapuram",
        "Tirunelveli"
    ],

    "Tirupattur": [
        "Ambur", "Natrampalli", "Tirupattur", "Vaniyambadi"
    ],

    "Tiruppur": [
        "Avinashi", "Dharapuram", "Kangeyam",
        "Madathukulam", "Palladam",
        "Tiruppur", "Udumalaipettai"
    ],

    "Tiruvallur": [
        "Avadi", "Gummidipoondi",
        "Ponneri", "Poonamallee",
        "Tiruttani", "Tiruvallur", "Uthukottai"
    ],

    "Tiruvannamalai": [
        "Arani", "Chengam", "Chetpet",
        "Jamunamarathur", "Kalasapakkam",
        "Polur", "Thandarampattu",
        "Tiruvannamalai", "Vandavasi"
    ],

    "Tiruvarur": [
        "Koothanallur", "Kudavasal",
        "Mannargudi", "Nannilam",
        "Needamangalam", "Thiruthuraipoondi",
        "Tiruvarur", "Valangaiman"
    ],

    "Vellore": [
        "Anaicut", "Gudiyatham",
        "Katpadi", "Pernambut",
        "Vellore"
    ],

    "Viluppuram": [
        "Gingee", "Kandachipuram",
        "Marakkanam", "Melmalayanur",
        "Tindivanam", "Vanur",
        "Vikravandi", "Viluppuram"
    ],

    "Virudhunagar": [
        "Aruppukkottai", "Kariapatti",
        "Rajapalayam", "Sattur",
        "Sivakasi", "Srivilliputhur",
        "Tiruchuli", "Virudhunagar"
    ]
}

import requests
from datetime import datetime


def fetch_weather(district, taluk):
    # Placeholder values (replace with real API response)
    weather_data = {
        "temperature": "32°C",
        "humidity": "68%",
        "condition": "Partly Cloudy",
        "wind": "12 km/h",
        "updated": datetime.now().strftime("%d-%m-%Y %H:%M:%S")
    }
    return weather_data

def grok_weather_summary(api_key, weather_data):
    if not api_key:
        return "(Grok summary disabled)"


    # Pseudo request – replace with real Grok endpoint
    summary = (
        f"Weather is {weather_data['condition']} with temperature "
        f"around {weather_data['temperature']}. Humidity is "
        f"{weather_data['humidity']}."
    )
    return summary

def get_weather_report(district, taluk, grok_key):
    data = fetch_weather(district, taluk)
    summary = grok_weather_summary(grok_key, data)


    return (
        f"🌦️ Weather Report – {taluk}, {district}\n"
        f"\n🌡️ Temperature: {data['temperature']}"
        f"\n💧 Humidity: {data['humidity']}"
        f"\n🌬️ Wind: {data['wind']}"
        f"\n☁️ Condition: {data['condition']}"
        f"\n🕒 Updated: {data['updated']}"
        f"\n\n🧠 AI Summary:\n{summary}"
    )

import gradio as gr


with gr.Blocks() as demo:
    gr.Markdown("""
    # 🌈 Tamil Nadu Taluk-wise Weather Monitor
    **Live updates every 5 minutes**
    Select District → Taluk → View Weather
    """)


    grok_key = gr.Textbox(label="Grok API Key", type="password")


    district = gr.Dropdown(
    choices=list(tn_taluks.keys()),
    label="District"
    )


    taluk = gr.Dropdown(label="Taluk")


    output = gr.Textbox(lines=12, label="Weather Report")


    def update_taluk(d):
        return gr.Dropdown(choices=tn_taluks[d])


    district.change(update_taluk, district, taluk)


    btn = gr.Button("🔄 Get Weather")
    btn.click(get_weather_report, [district, taluk, grok_key], output)


    gr.Markdown("""---
    🔁 **Auto-refresh every 5 minutes**
    Keep the page open for live monitoring.
    """)


    # Removed 'every' parameter to resolve TypeError. Automatic refresh will not occur.
    demo.load(
    fn=lambda d, t, k: get_weather_report(d, t, k),
    inputs=[district, taluk, grok_key],
    outputs=output
    )


    demo.launch()